name: Deploy Laravel App to AWS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
        extensions: 'pdo_sqlite'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Install Dependencies NPM
      run: npm install --silent
    - name: Build
      run: npm run build
    - name: Execute tests (Unit and Feature tests) via Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
  
  deploy:
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: SSH into EC2
      uses: ssh-action/ssh-key-action@v2
      with:
        host: http://ec2-18-221-204-190.us-east-2.compute.amazonaws.com/
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Run commands deploy
      run: |
        cd /var/www/url-shortener-spot2
        git pull
        npm install
        composer install
        npm run build
        php artisan migrate --seed
        sudo systemctl restart nginx
